### ISSUE TITLE
LCVR 1.1.0 - Valve Index Right Trigger functionality

### ISSUE THREAD

**Issue by Osborde** [DaXcess/LCVR#163]
The right trigger on Valve Index controllers no longer fulfills the left click action, though the "close finger" animation for the index finger works normally. Button may've been unbound during the update, not sure how to rectify this issue myself as others have stated Unity Editor controller configs are not sticking. I'm also not super knowledgeable on this subject myself.

**Comment by HylianSeven** [comment]
I just want to add that I am having the same issue. I was also unable to do some actions like climbing ladders.

**Comment by matejdro** [comment]
Yup, this makes the mod practically unplayable with 1.1.0 as user cannot perform the basic actions such as turning on the flashlight.

**Comment by Phil25** [comment]
I have the Index and can try to see what’s wrong, but I’ll only have time in 4-5h. I’ll open a PR when I find a fix.

Unless @DaXcess you already know what’s up then I’m open to testing.

**Comment by DaXcess** [comment]
> I have the Index and can try to see what’s wrong, but I’ll only have time in 4-5h. I’ll open a PR when I find a fix.
> 
> Unless @DaXcess you already know what’s up then I’m open to testing.

Index is not working because the controller bindings in LCVR-Controller-Profiles are no longer supported in 1.1.0 and require an update, so index users are using the bindings for Quest/Oculus controllers.

**Comment by Phil25** [comment]
This should be fixed after this PR is merged: https://github.com/DaXcess/LCVR-Controller-Profiles/pull/31

However, as of 1.1.2, `index` is not an officially supported controller profile, so you will have to go to LCVR configuration and change `ControllerBindingsOverrideProfile` to `index`. I'll update this comment if it gets officially added.

**NOTE**: Even if official support is added, Index controllers may have troubles being detected. Make sure to launch the game with SteamVR (or whatever else you're using) already open. This is not LCVR issue, I noticed it also happening for Blade & Sorcery, sometimes games require some help detecting input and this has worked so-so in my experience, including with Lethal Company.

**Comment by DaXcess** [comment]
@Phil25 I merged the controller profile, however I wanted to know a few things:

1. Is the building mode working properly (default is left + right grip, same on index?)
2. Can you charge a walkie talkie? (Yes this is something that can break depending on how the maps are ordered)

If this all seems fine then I'm also going to merge this profile into the mod itself so people with index will autodetect it and not be required to set an override.

**Comment by Phil25** [comment]
Build mode and storing works but walkie charging doesn't. I'll look for the correct order later today.

Are there any more things to be aware of? I assume the walkie doesn't work because it has a special left grip interaction.

**Comment by bavninja** [comment]
Pretty sure walkie charging got fixed in latest patch just after you uploaded the controller profile. At least for oculus controllers

**Comment by DaXcess** [comment]
> Build mode and storing works but walkie charging doesn't. I'll look for the correct order later today.
> 
> Are there any more things to be aware of? I assume the walkie doesn't work because it has a special left grip interaction.

Okay, so during testing yesterday I found that charging walkies doesn't work, because the TertiaryUse action is fired **before** the interact action. In the code, this means that a value (`timeSinceSwitchingSlots`) is set to zero, and then once the interact even fires it fails since the `timeSinceSwitchingSlots` must be larger than 0.2.

This was fixed on my end by moving the action map `Controls` **before** the action map `Movement` (which contain all of Lethal Company's actions)

**Comment by Phil25** [comment]
I did test on 1.1.0 just now, lemme check 1.1.2.

**Comment by DaXcess** [comment]
> > Build mode and storing works but walkie charging doesn't. I'll look for the correct order later today.
> > Are there any more things to be aware of? I assume the walkie doesn't work because it has a special left grip interaction.
> 
> Okay, so during testing yesterday I found that charging walkies doesn't work, because the TertiaryUse action is fired **before** the interact action. In the code, this means that a value (`timeSinceSwitchingSlots`) is set to zero, and then once the interact event fires it fails since the `timeSinceSwitchingSlots` must be larger than 0.2.
> 
> This was fixed on my end by moving the action map `Controls` **before** the action map `Movement` (which contain all of Lethal Company's actions)

An example of a profile I fixed: https://github.com/DaXcess/LCVR-Controller-Profiles/commit/067ef95750e3c4838cec0d638bd47f48c474c597

**Comment by Phil25** [comment]
Okay I misunderstood that it might've been fixed in code already, checked bindings on 1.1.2 and walkie charging is still broken.

> An example of a profile I fixed: [DaXcess/LCVR-Controller-Profiles@067ef95](https://github.com/DaXcess/LCVR-Controller-Profiles/commit/067ef95750e3c4838cec0d638bd47f48c474c597)

Thanks for the reference, I'll play around with it in a few hours.

**Comment by Phil25** [comment]
@DaXcess Confirming Index bindings work on 1.1.3 with your fix, including triggers, build mode and walkie charging.

I _think_ the bindings fix might've changed the controls for build mode a bit. I found that the only consistent way of moving something is pressing both grips, releasing the left one while holding the right, then tapping the left grip to place something down.

Getting into build mode works well regardless, but when trying to place a prop down it seems to prioritize cancelling build mode when you tap the right grip, even though you're trying to tap both. Again, I don't exactly know if it were like this before.

**Comment by DrunkOnSuccess** [comment]
It's still broken in the latest update, it's not a detection thing it's a mod thing. The triggers work in the menu, on the terminal, they work where they are meant to except for when I'm just trying to use a flashlight.

**Comment by HylianSeven** [comment]
> It's still broken in the latest update, it's not a detection thing it's a mod thing. The triggers work in the menu, on the terminal, they work where they are meant to except for when I'm just trying to use a flashlight.

If you haven't already, make sure in the config file for the mod, you set ControllerBindingsOverrideProfile to "index". I did this myself and it works. I'm able to use the flashlight, use the walkie talkie, etc.

**Comment by DrunkOnSuccess** [comment]
If this fixes it I'm going to be very annoyed.

> > It's still broken in the latest update, it's not a detection thing it's a mod thing. The triggers work in the menu, on the terminal, they work where they are meant to except for when I'm just trying to use a flashlight.
> 
> If you haven't already, make sure in the config file for the mod, you set ControllerBindingsOverrideProfile to "index". I did this myself and it works. I'm able to use the flashlight, use the walkie talkie, etc.

**Comment by Phil25** [comment]
> It's still broken in the latest update, it's not a detection thing it's a mod thing. The triggers work in the menu, on the terminal, they work where they are meant to except for when I'm just trying to use a flashlight.

This is just the way the bindings work. There are different actions for what you do during gameplay and different ones when you're in the menu. The Index detection fails and it just so happens that the default bindings LCVR falls back to make most of the functionality work, but not all.

Now, it is to some extent an issue with the mod, but it itself relies on Unity's Open​XR Input plugin to detect the controllers for it. That plugin is simply faulty for the Index, especially when SteamVR isn't running. Like I mentioned in another comment, I saw the same issue for Blade & Sorcery and noticed it in LCVR too when running with and without SteamVR (although even with SteamVR detection isn't consistent).

The best way to fix this is someone with an Index could sit down and experiment with ways to detect the controllers consistently. I took a brief look around but couldn't find anything good from a glace (I also have no experience with VR development). If I'll have some time I could research the topic a bit and find a good solution but I'm not willing to promise anything.

**Comment by DrunkOnSuccess** [comment]
> > It's still broken in the latest update, it's not a detection thing it's a mod thing. The triggers work in the menu, on the terminal, they work where they are meant to except for when I'm just trying to use a flashlight.
> 
> This is just the way the bindings work. There are different actions for what you do during gameplay and different ones when you're in the menu. The Index detection fails and it just so happens that the default bindings LCVR falls back to make most of the functionality work, but not all.
> 
> Now, it is to some extent an issue with the mod, but it itself relies on Unity's Open​XR Input plugin to detect the controllers for it. That plugin is simply faulty for the Index, especially when SteamVR isn't running. Like I mentioned in another comment, I saw the same issue for Blade & Sorcery and noticed it in LCVR too when running with and without SteamVR (although even with SteamVR detection isn't consistent).
> 
> The best way to fix this is someone with an Index could sit down and experiment with ways to detect the controllers consistently. I took a brief look around but couldn't find anything good from a glace (I also have no experience with VR development). If I'll have some time I could research the topic a bit and find a good solution but I'm not willing to promise anything.

Except.. It's not. The button wasn't bound fullstop, once I changed the config all was well. Nothing to do with Unity's OpenXR.

**Comment by Phil25** [comment]
> Except.. It's not. The button wasn't bound fullstop, once I changed the config all was well.

Don't think of it in terms of buttons, but rather specific in-game actions. One kind of trigger input can be assigned to clicking something in the menu, an alternative trigger input can be assigned to using an item in game. Both of those inputs correspond to the same specific button, but are addressed differently (for their specific reasons). In the default bindings one of those inputs just doesn't work for Index controllers.

> Nothing to do with Unity's OpenXR.

Check your BepInEx logs, I bet there's a message saying that VR controllers couldn't be identified and LCVR is falling back to default bindings.

**Comment by DrunkOnSuccess** [comment]
> > Except.. It's not. The button wasn't bound fullstop, once I changed the config all was well.
> 
> Don't think of it in terms of buttons, but rather specific in-game actions. One kind of trigger input can be assigned to clicking something in the menu, an alternative trigger input can be assigned to using an item in game. Both of those inputs correspond to the same specific button, but are addressed differently (for their specific reasons). In the default bindings one of those inputs just doesn't work for Index controllers.
> 
> > Nothing to do with Unity's OpenXR.
> 
> Check your BepInEx logs, I bet there's a message saying that VR controllers couldn't be identified and LCVR is falling back to default bindings.

Correct, it doesn't work for index controllers, because the mod was not bound for index controllers, it has to be done manually.

**Comment by Phil25** [comment]
Correct, it has to be done manually because Unity's OpenXR fails to detect Index controllers, which is something the mod relies on.

**Comment by DrunkOnSuccess** [comment]
Nothing in the logs says anything along the lines of "Index can't be indentified, falling back to default" I don't know what to tell you. I'm not arguing to be annoying it's just I think the issue isn't in controller identification. By default the right trigger should still activate equipment on any VR controller, all of them have triggers, but it doesn't.

**Comment by DrunkOnSuccess** [comment]
> Nothing in the logs says anything along the lines of "Index can't be indentified, falling back to default" I don't know what to tell you. I'm not arguing to be annoying it's just I think the issue isn't in controller identification. By default the right trigger should still activate equipment on any VR controller, all of them have triggers, but it doesn't.

Another thing too, when the right trigger is not working finger tracking still does, a feature exclusive to Index controllers. It knows what it's using, it **_is_** detecting the Index controllers, the trigger just doesn't work.

**Comment by Phil25** [comment]
My point is that you're overriding the bindings by setting `ControllerBindingsOverrideProfile` yourself. You **shouldn't** need to do it, because LCVR attempts to identifiy the controllers and set it to `index` itself, but fails. When it fails, the configuration falls back to the default bindings, where most of the features (like menu clicking or index finger touch detection) work by happenstance, with the exception of using in-game items, which happens to be pressing the trigger button.

Ultimately I agree, most of the controls are there but the trigger doesn't work. From the user's perspective it's as simple as that, and really we're just discussing semantics at this point.

**Comment by DrunkOnSuccess** [comment]
Yes, I agree but this is where I'm getting confused over what the actual cause of the issue is. I can see how it would be a detection issue, and let's say that you're 100% correct (which you might be) the trigger, above all, should work. It is the one control that all VR controllers share, I'm shocked that every other control works fine by happenstance besides the trigger, the most common and basic button. It's baffling.

This mod stuff is confusing mang.

**Comment by Phil25** [comment]
I did some digging and it seems that devices as detected by Unity are not ready when profile detection occurs, at least for Index controllers, but are added around 1 second too late. I explained it in more detail in https://github.com/DaXcess/LCVR/pull/180, where I was unable to find a proper solution.

**Comment by DaXcess** [comment]
Cleaning up old issues
This was fixed a while back in `dev` with fixed automatic controller detection
